#!/bin/bash 
  
cd
rm -rf ccminer-arm32bit
git clone https://github.com/saengx/ccminer-arm32bit 
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/ccminer-arm32bit/mobile-mining/set-miner
cd
cd ../etc/mobile-mining/setip
cp -r ip.json set-cpu.json /../root/ccminer-arm32bit/mobile-mining/setip
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-file edit-miner run-miner restore backup auto down-grade info set-miner update start
cd
cd ccminer-arm32bit 
chmod +x setupdate.sh
sh setupdate.sh
